#!/usr/bin/env bash

cwd=$(pwd)

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $script_dir

nsbl-inventory --repos {{ role_repo_paths }} --config {{ nsbl_script_configs }} $@

cd $cwd

exit 0
